// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: proto/keepalive.proto

package packge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KeepAliveClient is the client API for KeepAlive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeepAliveClient interface {
	MakeKeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error)
}

type keepAliveClient struct {
	cc grpc.ClientConnInterface
}

func NewKeepAliveClient(cc grpc.ClientConnInterface) KeepAliveClient {
	return &keepAliveClient{cc}
}

func (c *keepAliveClient) MakeKeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error) {
	out := new(KeepAliveResponse)
	err := c.cc.Invoke(ctx, "/keepalive.KeepAlive/MakeKeepAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeepAliveServer is the server API for KeepAlive service.
// All implementations must embed UnimplementedKeepAliveServer
// for forward compatibility
type KeepAliveServer interface {
	MakeKeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveResponse, error)
	mustEmbedUnimplementedKeepAliveServer()
}

// UnimplementedKeepAliveServer must be embedded to have forward compatible implementations.
type UnimplementedKeepAliveServer struct {
}

func (UnimplementedKeepAliveServer) MakeKeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeKeepAlive not implemented")
}
func (UnimplementedKeepAliveServer) mustEmbedUnimplementedKeepAliveServer() {}

// UnsafeKeepAliveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeepAliveServer will
// result in compilation errors.
type UnsafeKeepAliveServer interface {
	mustEmbedUnimplementedKeepAliveServer()
}

func RegisterKeepAliveServer(s grpc.ServiceRegistrar, srv KeepAliveServer) {
	s.RegisterService(&KeepAlive_ServiceDesc, srv)
}

func _KeepAlive_MakeKeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeepAliveServer).MakeKeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keepalive.KeepAlive/MakeKeepAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeepAliveServer).MakeKeepAlive(ctx, req.(*KeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeepAlive_ServiceDesc is the grpc.ServiceDesc for KeepAlive service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeepAlive_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keepalive.KeepAlive",
	HandlerType: (*KeepAliveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeKeepAlive",
			Handler:    _KeepAlive_MakeKeepAlive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/keepalive.proto",
}
