// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/loraTransaction.proto

package packge

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoraRequest struct {
	IdEdge               int32                 `protobuf:"varint,1,opt,name=idEdge,proto3" json:"idEdge,omitempty"`
	IdNodo               int32                 `protobuf:"varint,2,opt,name=idNodo,proto3" json:"idNodo,omitempty"`
	Input1               int32                 `protobuf:"varint,3,opt,name=input1,proto3" json:"input1,omitempty"`
	Input2               int32                 `protobuf:"varint,4,opt,name=input2,proto3" json:"input2,omitempty"`
	Output               int32                 `protobuf:"varint,5,opt,name=output,proto3" json:"output,omitempty"`
	AlarmBattery         bool                  `protobuf:"varint,6,opt,name=alarm_battery,json=alarmBattery,proto3" json:"alarm_battery,omitempty"`
	AlarmPower           bool                  `protobuf:"varint,7,opt,name=alarm_power,json=alarmPower,proto3" json:"alarm_power,omitempty"`
	SensorError          bool                  `protobuf:"varint,8,opt,name=sensor_error,json=sensorError,proto3" json:"sensor_error,omitempty"`
	Sensors              []*LoraRequest_Sensor `protobuf:"bytes,9,rep,name=sensors,proto3" json:"sensors,omitempty"`
	LastUpdated          string                `protobuf:"bytes,10,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LoraRequest) Reset()         { *m = LoraRequest{} }
func (m *LoraRequest) String() string { return proto.CompactTextString(m) }
func (*LoraRequest) ProtoMessage()    {}
func (*LoraRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce14830d294b7921, []int{0}
}

func (m *LoraRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoraRequest.Unmarshal(m, b)
}
func (m *LoraRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoraRequest.Marshal(b, m, deterministic)
}
func (m *LoraRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoraRequest.Merge(m, src)
}
func (m *LoraRequest) XXX_Size() int {
	return xxx_messageInfo_LoraRequest.Size(m)
}
func (m *LoraRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoraRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoraRequest proto.InternalMessageInfo

func (m *LoraRequest) GetIdEdge() int32 {
	if m != nil {
		return m.IdEdge
	}
	return 0
}

func (m *LoraRequest) GetIdNodo() int32 {
	if m != nil {
		return m.IdNodo
	}
	return 0
}

func (m *LoraRequest) GetInput1() int32 {
	if m != nil {
		return m.Input1
	}
	return 0
}

func (m *LoraRequest) GetInput2() int32 {
	if m != nil {
		return m.Input2
	}
	return 0
}

func (m *LoraRequest) GetOutput() int32 {
	if m != nil {
		return m.Output
	}
	return 0
}

func (m *LoraRequest) GetAlarmBattery() bool {
	if m != nil {
		return m.AlarmBattery
	}
	return false
}

func (m *LoraRequest) GetAlarmPower() bool {
	if m != nil {
		return m.AlarmPower
	}
	return false
}

func (m *LoraRequest) GetSensorError() bool {
	if m != nil {
		return m.SensorError
	}
	return false
}

func (m *LoraRequest) GetSensors() []*LoraRequest_Sensor {
	if m != nil {
		return m.Sensors
	}
	return nil
}

func (m *LoraRequest) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

type LoraRequest_Sensor struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                float32  `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoraRequest_Sensor) Reset()         { *m = LoraRequest_Sensor{} }
func (m *LoraRequest_Sensor) String() string { return proto.CompactTextString(m) }
func (*LoraRequest_Sensor) ProtoMessage()    {}
func (*LoraRequest_Sensor) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce14830d294b7921, []int{0, 0}
}

func (m *LoraRequest_Sensor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoraRequest_Sensor.Unmarshal(m, b)
}
func (m *LoraRequest_Sensor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoraRequest_Sensor.Marshal(b, m, deterministic)
}
func (m *LoraRequest_Sensor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoraRequest_Sensor.Merge(m, src)
}
func (m *LoraRequest_Sensor) XXX_Size() int {
	return xxx_messageInfo_LoraRequest_Sensor.Size(m)
}
func (m *LoraRequest_Sensor) XXX_DiscardUnknown() {
	xxx_messageInfo_LoraRequest_Sensor.DiscardUnknown(m)
}

var xxx_messageInfo_LoraRequest_Sensor proto.InternalMessageInfo

func (m *LoraRequest_Sensor) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *LoraRequest_Sensor) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type LoraResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Confirmation         bool     `protobuf:"varint,2,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoraResponse) Reset()         { *m = LoraResponse{} }
func (m *LoraResponse) String() string { return proto.CompactTextString(m) }
func (*LoraResponse) ProtoMessage()    {}
func (*LoraResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce14830d294b7921, []int{1}
}

func (m *LoraResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoraResponse.Unmarshal(m, b)
}
func (m *LoraResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoraResponse.Marshal(b, m, deterministic)
}
func (m *LoraResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoraResponse.Merge(m, src)
}
func (m *LoraResponse) XXX_Size() int {
	return xxx_messageInfo_LoraResponse.Size(m)
}
func (m *LoraResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoraResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoraResponse proto.InternalMessageInfo

func (m *LoraResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoraResponse) GetConfirmation() bool {
	if m != nil {
		return m.Confirmation
	}
	return false
}

type ListLoraRequest struct {
	ListDevice           []*LoraRequest `protobuf:"bytes,1,rep,name=listDevice,proto3" json:"listDevice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListLoraRequest) Reset()         { *m = ListLoraRequest{} }
func (m *ListLoraRequest) String() string { return proto.CompactTextString(m) }
func (*ListLoraRequest) ProtoMessage()    {}
func (*ListLoraRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce14830d294b7921, []int{2}
}

func (m *ListLoraRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLoraRequest.Unmarshal(m, b)
}
func (m *ListLoraRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLoraRequest.Marshal(b, m, deterministic)
}
func (m *ListLoraRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLoraRequest.Merge(m, src)
}
func (m *ListLoraRequest) XXX_Size() int {
	return xxx_messageInfo_ListLoraRequest.Size(m)
}
func (m *ListLoraRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLoraRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLoraRequest proto.InternalMessageInfo

func (m *ListLoraRequest) GetListDevice() []*LoraRequest {
	if m != nil {
		return m.ListDevice
	}
	return nil
}

type ListLoraResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Confirmation         bool     `protobuf:"varint,2,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLoraResponse) Reset()         { *m = ListLoraResponse{} }
func (m *ListLoraResponse) String() string { return proto.CompactTextString(m) }
func (*ListLoraResponse) ProtoMessage()    {}
func (*ListLoraResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce14830d294b7921, []int{3}
}

func (m *ListLoraResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLoraResponse.Unmarshal(m, b)
}
func (m *ListLoraResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLoraResponse.Marshal(b, m, deterministic)
}
func (m *ListLoraResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLoraResponse.Merge(m, src)
}
func (m *ListLoraResponse) XXX_Size() int {
	return xxx_messageInfo_ListLoraResponse.Size(m)
}
func (m *ListLoraResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLoraResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListLoraResponse proto.InternalMessageInfo

func (m *ListLoraResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListLoraResponse) GetConfirmation() bool {
	if m != nil {
		return m.Confirmation
	}
	return false
}

func init() {
	proto.RegisterType((*LoraRequest)(nil), "packge.LoraRequest")
	proto.RegisterType((*LoraRequest_Sensor)(nil), "packge.LoraRequest.Sensor")
	proto.RegisterType((*LoraResponse)(nil), "packge.LoraResponse")
	proto.RegisterType((*ListLoraRequest)(nil), "packge.ListLoraRequest")
	proto.RegisterType((*ListLoraResponse)(nil), "packge.ListLoraResponse")
}

func init() {
	proto.RegisterFile("proto/loraTransaction.proto", fileDescriptor_ce14830d294b7921)
}

var fileDescriptor_ce14830d294b7921 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x49, 0xbb, 0x66, 0xe9, 0x4b, 0x50, 0x27, 0x77, 0x02, 0x2b, 0x1c, 0x08, 0xe1, 0x92,
	0x53, 0x26, 0x32, 0xce, 0x1c, 0xa6, 0x0d, 0x21, 0x54, 0x10, 0x18, 0xb8, 0x70, 0x99, 0xbc, 0xc4,
	0x54, 0xd1, 0xd2, 0xd8, 0xd8, 0xce, 0xd0, 0xfe, 0x75, 0x4e, 0xc8, 0xf6, 0x52, 0x1c, 0xd1, 0x1b,
	0x37, 0x7f, 0x3f, 0x7f, 0xef, 0xf9, 0xf9, 0x73, 0x02, 0xcf, 0x84, 0xe4, 0x9a, 0x9f, 0x75, 0x5c,
	0xd2, 0xaf, 0x92, 0xf6, 0x8a, 0xd6, 0xba, 0xe5, 0x7d, 0x69, 0x29, 0x0a, 0x05, 0xad, 0x6f, 0xb7,
	0x2c, 0xff, 0x3d, 0x83, 0x78, 0xc3, 0x25, 0x25, 0xec, 0xe7, 0xc0, 0x94, 0x46, 0x4f, 0x20, 0x6c,
	0x9b, 0xab, 0x66, 0xcb, 0x70, 0x90, 0x05, 0xc5, 0x82, 0x3c, 0x28, 0xc7, 0x3f, 0xf2, 0x86, 0xe3,
	0xd9, 0xc8, 0x8d, 0xb2, 0xbc, 0x17, 0x83, 0x7e, 0x85, 0xe7, 0x0f, 0xdc, 0xaa, 0x3d, 0xaf, 0xf0,
	0x91, 0xc7, 0x2b, 0xc3, 0xf9, 0xa0, 0xc5, 0xa0, 0xf1, 0xc2, 0x71, 0xa7, 0xd0, 0x4b, 0x78, 0x4c,
	0x3b, 0x2a, 0x77, 0xd7, 0x37, 0x54, 0x6b, 0x26, 0xef, 0x71, 0x98, 0x05, 0x45, 0x44, 0x12, 0x0b,
	0x2f, 0x1c, 0x43, 0xcf, 0x21, 0x76, 0x26, 0xc1, 0x7f, 0x31, 0x89, 0x8f, 0xad, 0x05, 0x2c, 0xfa,
	0x64, 0x08, 0x7a, 0x01, 0x89, 0x62, 0xbd, 0xe2, 0xf2, 0x9a, 0x49, 0xc9, 0x25, 0x8e, 0xac, 0x23,
	0x76, 0xec, 0xca, 0x20, 0xf4, 0x1a, 0x8e, 0x9d, 0x54, 0x78, 0x99, 0xcd, 0x8b, 0xb8, 0x4a, 0x4b,
	0x17, 0x45, 0xe9, 0xc5, 0x50, 0x7e, 0xb1, 0x16, 0x32, 0x5a, 0x51, 0x06, 0x71, 0x47, 0x95, 0xfe,
	0x26, 0x1a, 0xaa, 0x59, 0x83, 0x21, 0x0b, 0x8a, 0x25, 0xf1, 0x51, 0x5a, 0x41, 0xe8, 0x8a, 0x10,
	0x82, 0x23, 0x7d, 0x2f, 0xc6, 0x00, 0xed, 0x1a, 0x9d, 0xc2, 0xe2, 0x8e, 0x76, 0x03, 0xb3, 0xe9,
	0xcd, 0x88, 0x13, 0xf9, 0x25, 0x24, 0xee, 0x50, 0x25, 0x78, 0xaf, 0x18, 0x3a, 0x81, 0xf9, 0x4e,
	0x6d, 0x6d, 0xe1, 0x92, 0x98, 0x25, 0xca, 0x21, 0xa9, 0x79, 0xff, 0xa3, 0x95, 0x3b, 0x6a, 0x1e,
	0xcf, 0x96, 0x47, 0x64, 0xc2, 0xf2, 0xb7, 0xb0, 0xda, 0xb4, 0x4a, 0xfb, 0xaf, 0x78, 0x0e, 0xd0,
	0xb5, 0x4a, 0x5f, 0xb2, 0xbb, 0xb6, 0x36, 0x83, 0x98, 0x7b, 0xae, 0x0f, 0xdc, 0x93, 0x78, 0xb6,
	0xfc, 0x1d, 0x9c, 0xfc, 0xed, 0xf3, 0x3f, 0x13, 0x55, 0x9f, 0x61, 0xb5, 0x99, 0x7e, 0x75, 0xe8,
	0x0d, 0xac, 0x3e, 0xd0, 0x5b, 0xe6, 0xa3, 0x43, 0x03, 0xa5, 0xa7, 0x53, 0xe8, 0xc6, 0xc8, 0x1f,
	0x55, 0x14, 0xd6, 0xe3, 0x70, 0x7e, 0x8f, 0xf7, 0xb0, 0x36, 0x6d, 0xcd, 0x96, 0x8f, 0x9f, 0xee,
	0xbb, 0x4c, 0x83, 0x49, 0xf1, 0xbf, 0x1b, 0xe3, 0x11, 0x17, 0xf0, 0x3d, 0x2a, 0xcf, 0xdc, 0xf6,
	0x4d, 0x68, 0xff, 0x92, 0xf3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x0c, 0x41, 0x98, 0x44,
	0x03, 0x00, 0x00,
}
